Repository kyma-project/directory-size-exporter, pull requests merged in 2023-12, with the labels that each got.

#36 Update module-name in the sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#38 chore: Migrate jobs to gh action
  .github/template/prepare-checks/action.yaml
  .github/workflows/markdown-link-check.yml
  .github/workflows/pull-code-checks.yml
  .github/workflows/pull-governance.yml
  .golangci.yaml
Labels: size/M, lgtm, area/ci, cla: yes

#39 chore: Run docu checks on docu changes
  .github/template/setup-golang/action.yaml
  .github/workflows/pull-code-checks.yml
  .github/workflows/pull-docu-checks.yml
  .github/workflows/pull-github-checks.yml
Labels: size/M, lgtm, area/ci, kind/chore, cla: yes
