Repository kyma-project/directory-size-exporter, pull requests merged in 2024-10, with the labels that each got.

#74 chore: Introduce all checks passed workflow
  .github/pull-request-template.md
  .github/workflows/build-image.yml
  .github/workflows/pr-all-checks-passed.yml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-github-checks.yml
Labels: size/M, lgtm, area/ci, kind/chore, cla: yes

#75 chore: Fix label check
  .github/workflows/pr-github-checks.yml
Labels: lgtm, size/S, area/ci, kind/chore, cla: yes

#76 chore: Fix failing gh actions
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
Labels: lgtm, size/S, area/ci, kind/chore, cla: yes

#79 fix: Implement graceful shutdown
  Dockerfile
  main.go
Labels: kind/bug, size/M, area/quality

#81 chore: Harmonize dependabot config with telemetry-manager
  .github/dependabot.yml
Labels: size/M, area/ci, kind/chore, cla: yes
