Repository kyma-project/directory-size-exporter, pull requests merged in 2024-08, with the labels that each got.

#60 chore: Prepare Repository for Repo-rules
  .github/workflows/build-image.yml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-github-checks.yml
Labels: lgtm, area/ci, size/L, kind/chore, cla: yes

#66 chore: Replace legacy logging lib with slog
  go.mod
  go.sum
  internal/exporter/exporter.go
  internal/exporter/exporter_test.go
  main.go
Labels: lgtm, area/logging, size/L, kind/chore, cla: yes

#61 chore: Change Dockerfile base image from bookworm to alpine
  Dockerfile
Labels: size/XS, area/dependency, lgtm, kind/chore, cla: yes
