Repository kyma-project/directory-size-exporter, pull requests merged in 2024-12, with the labels that each got.

#88 chore: Use merge group trigger for merge queue CI
  .github/workflows/build-image.yml
  .github/workflows/pr-all-checks-passed.yml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-github-checks.yml
Labels: size/XS, lgtm, area/ci, kind/chore, cla: yes

#89 chore: Remove merge_group trigger for some workflows
  .github/workflows/build-image.yml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-github-checks.yml
Labels: size/XS, lgtm, area/ci, kind/chore, cla: yes

#87 chore: Remove outdated OWNERS file
  OWNERS
  OWNERS_ALIASES
Labels: size/M, lgtm, kind/chore, area/quality, cla: yes

#92 chore: Remove delay on allcheckspassed action
  .github/workflows/pr-all-checks-passed.yml
Labels: size/XS, lgtm, area/ci, kind/chore, cla: yes

#91 chore: Update golang to 1.23.4 and alpine to 3.21
  Dockerfile
  go.mod
  internal/tools/go.mod
Labels: size/XS, area/dependency, lgtm, kind/chore, cla: yes
