Repository kyma-project/directory-size-exporter, pull requests merged in 2025-03, with the labels that each got.

#118 chore: add additional permissions for image builder
  .github/workflows/build-image.yml
Labels: kind/chore, size/XS, area/ci

#122 chore: Update x-net and x-tools lib
  go.mod
  go.sum
  internal/tools/go.mod
  internal/tools/go.sum
Labels: area/dependency, kind/chore

#126 chore: ensure PR title subject doesn't start with an uppercase character
  .github/workflows/pr-github-checks.yml
Labels: kind/chore, area/ci
