Repository kyma-project/directory-size-exporter, pull requests merged in 2025-02, with the labels that each got.

#101 chore: Rename security scanners config fields
  sec-scanners-config.yaml
Labels: size/XS, lgtm, kind/chore, area/cli, cla: yes

#100 chore: Update to golang 1.23.6 + add renovate
  Dockerfile
  go.mod
  go.sum
  internal/tools/go.mod
  renovate.json
Labels: size/M, area/dependency, lgtm, kind/chore, cla: yes

#106 chore: Enable label and milestone automation
  .github/workflows/pr-github-checks.yml
  .github/workflows/titleprefix_to_label.json
  renovate.json
Labels: lgtm, area/ci, size/L, kind/chore, cla: yes

#111 chore: enable gha update, disable dependabot
  .github/dependabot.yml
  renovate.json
Labels: kind/chore, lgtm, cla: yes, area/ci, size/M
